### ISSUE TITLE
SET command not found 

### ISSUE THREAD

**Issue by 455631680** [pookpal/star-initReact-example#4]
> react-pookpal@1.0.0 dev /Users/Deg/Code&Repository/Front End/WebMobile/star-initReact-example-master
> npm run build:i18n-js && SET BABEL_ENV=development && webpack-dev-server --progress --colors --hot

> react-pookpal@1.0.0 build:i18n-js /Users/Deg/Code&Repository/Front End/WebMobile/star-initReact-example-master
> npm run build:i18n-messages && babel-node --presets es2015 scripts/translate.js

> react-pookpal@1.0.0 build:i18n-messages /Users/Deg/Code&Repository/Front End/WebMobile/star-initReact-example-master
> rimraf i18n-messages && BABEL_ENV=i18n babel --quiet src > /dev/null

sh: SET: command not found

**Comment by pookpal** [comment]
已经解决，请重新clone项目运行
